### ISSUE TITLE
Some flags not working

### ISSUE THREAD

**Issue by mblasi** [ericm/stonks#10]
Neither `--days 10` nor `--week` work.

```
stonks --days 10                                                                                                                                                                      at  13:10:50
Mercadolibre inc:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ MELI | 824.99 USD (1.26%) on Fri 22/05/2020 13:11 GMT | Prev: 814.71 | NMS            ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃827.44│                                                                                ┃
┃825.56│                ╱ ▁    ╱ʌ   ╱ ʌ                                                 ┃
┃823.67│   ▁    ╱───────   ╲  ╱  ╲ ╱   ╲ ╲                                              ┃
┃821.79│    ╲  ╱            ╲╱                                                          ┃
┃819.91│     ╲╱                                                                         ┃
┃818.03│                                                                                ┃
┃816.14│                                                                                ┃
┃814.26│  ╱                                                                             ┃
┃812.38│ ╱                                                                              ┃
┃810.50│─                                                                               ┃
┃808.61│                                                                                ┃
┃806.73│                                                                                ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃       10.30am  11.15am  12.00pm  12.45pm                                              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

**Comment by ericm** [comment]
That should have been fixed in `1.0.4`. Can you do `stonks -v`

**Comment by mblasi** [comment]
Thank you! It is 1.0.1, I just cloned and make&make install some days
ago... from master...
I'll update my clone.

Saludos,
Matías.

**Comment by mblasi** [comment]
Nice, I pulled and now I have 1.0.5 version.

It works with `-w` but not with `-d 5`

  ~/workspace/stonks on   master ❯ stonks -d 5

                                       at  18:32:15
Mercadolibre inc:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ MELI | 793.93 USD (2.44% | 18.88) on Mon 18/05/2020 16:45 | Prev: 775.05
| NMS        ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃804.65│
             ┃
┃803.10│               ʌ
             ┃
┃801.55│                ╲
            ┃
┃800.00│              ╱  ╲
             ┃
┃798.44│             ╱    ▁                                    ╱ ────
    ʌ       ┃
┃796.89│           ╱╱      ╲ ▁                              ╱ ╱      ╲
    ╱ ╲      ┃
┃795.34│          ╱           ╲                           ╱╱          ╲▁
   ╱   ╲     ┃
┃793.79│─       ╱╱             ╲                 ╱────   ╱              ╲
────     ╲    ┃
┃792.24│ ╲ ▁   ╱                ▁               ╱     ╲ ╱
            ┃
┃790.69│    ╲ ╱                  ╲ ▔    ╱ʌ   ╱ ╱
             ┃
┃789.13│                            ╲  ╱  ╲ ╱
            ┃
┃787.58│                             ╲╱
            ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃       10.30am  11.15am  12.00pm  12.45pm   1.30pm   2.15pm   3.00pm
3.45pm   4.30pm ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

  ~/workspace/stonks on   master ❯ stonks -w

                                       at  18:32:17
Mercadolibre inc:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ MELI | 841.17 USD (8.53% | 66.12) on Fri 22/05/2020 16:30 | Prev: 775.05
| NMS        ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃843.38│
             ┃
┃838.60│                              ʌ
─────           ┃
┃833.82│                             ╱ ╲                               ╱
             ┃
┃829.04│                            ╱   ▁                            ╱╱
            ┃
┃824.26│                                 ╲     ╱ʌ               ▁  ╱╱
            ┃
┃819.48│                   ╱▁             ─────  ╲             ╱ ╲╱
            ┃
┃814.71│                 ╱╱  ╲▔                   ▁   ─────────
            ┃
┃809.93│               ╱╱      ╲▔  ╱               ╲ ╱
             ┃
┃805.15│              ╱          ╲╱                 ╱
            ┃
┃800.37│
             ┃
┃795.59│ ╱▁    ╱▁    ╱
             ┃
┃790.81│─  ╲───  ╲───
            ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃       18 May          19 May          20 May          21 May          22
May          ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

  ~/workspace/stonks on   master ❯

                                       at  18:32:23


Saludos,
Matías.

**Comment by ericm** [comment]
It seems to be working to me. `-d` will give stocks from X days ago (as seen above the 18th). Maybe I should make that clearer in the help message

**Comment by mblasi** [comment]
I send two samples: first with `-d 5` which just shows today stats, second
with `-w` which works great, showing stats since 18th

Saludos,
Matías.

**Comment by ericm** [comment]
Are you sure? The date I'm seeing is the 18th for `-d 5`
![image](https://user-images.githubusercontent.com/29894839/82742214-12b63980-9d53-11ea-8785-2dc2b8274783.png)
Is the issue with the graph not changing?

**Comment by mblasi** [comment]
Ohhh I se... excuseme... I misunderstood the flag... I expected that `-d 7`
be the same than `-w`... said that, it´s working as expected.


Saludos,
Matías.
