### ISSUE TITLE
Stonks: command not found

### ISSUE THREAD

**Issue by Jacksole** [ericm/stonks#13]
I'm running into this issue where I'm attempted to use this program but I get no command found. I cloned the repo. I ran make and make install. However, when I run i.e. stonks -s AMD -n "Advanced Micro Devices" I get command not found. Also, I tried to run make and make install as sudo but I get this message 

go get
go build -v -o stonks
go install -v
make: go: Command not found
Makefile:12: recipe for target 'install' failed
make: *** [install] Error 127 (which looks like it can't find  a complier)

I have go installed, with a set GO PATH and gcc and c++ in the $PATH(along with go) so I'm not sure the problem could be. I am on WSL if that makes a differences

**Comment by ericm** [comment]
Are you building in or outside the GOPATH? This is a go mod project so make sure you're outside it

**Comment by Jacksole** [comment]
How would I be able to check that?

**Comment by ericm** [comment]
Type `go env GOPATH` and make sure the source code is outside of it.

**Comment by ericm** [comment]
If you are and it's still not working, try running `export PATH=$PATH:/usr/local/go/bin` before `make`

**Comment by Jacksole** [comment]
Hey sorry, I haven't replied back but I was able to get it working. I didn't use ./stonks when I typed in the command stonks. I created an aliases and it's all set not. Thanks for your help
