### ISSUE TITLE
Filename: /Users/montanaflynn/.config/stonks requires valid extension.

### ISSUE THREAD

**Issue by montanaflynn** [ericm/stonks#2]
I get this error trying to save a favorite:

```
$ stonks -s AMD -n "Advanced Micro Devices"
Filename: /Users/montanaflynn/.config/stonks requires valid extension.
```

**Comment by ericm** [comment]
seems like a macos issue. Temporarily, see if running that command with sudo fixes it

**Comment by montanaflynn** [comment]
@ericm nope, I think it's a viper issue:

https://github.com/spf13/viper/issues/829
